# Generated by Django 3.1 on 2022-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=32, verbose_name='手机')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书籍名称')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('info', models.CharField(max_length=64, verbose_name='书籍详情')),
                ('authors', models.ManyToManyField(to='bookapp.Author')),
            ],
        ),
    ]
